// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("MassTransit.EventStore")]
[assembly: AssemblyCompanyAttribute("Alexey Zimarev")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2017 Alexey Zimarev")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0-unstable.0+Branch.develop.Sha.0335bb3b1ea24400bd48f36ce75dc3bb4b00f098")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "MassTransit.EventStore";
        internal const System.String AssemblyCompany = "Alexey Zimarev";
        internal const System.String AssemblyCopyright = "Copyright © 2017 Alexey Zimarev";
        internal const System.String AssemblyVersion = "0.1.0.0";
        internal const System.String AssemblyFileVersion = "0.1.0.0";
        internal const System.String AssemblyInformationalVersion = "0.1.0-unstable.0+Branch.develop.Sha.0335bb3b1ea24400bd48f36ce75dc3bb4b00f098";
    }
}
