// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("MassTransit.EventStoreIntegration")]
[assembly: AssemblyCompanyAttribute("Alexey Zimarev")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2018 Alexey Zimarev")]
[assembly: AssemblyVersionAttribute("1.0.1.0")]
[assembly: AssemblyFileVersionAttribute("1.0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.1+6.Branch.master.Sha.36961326774d41c78a6d083fb83fa8931507bb6e")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "MassTransit.EventStoreIntegration";
        internal const System.String AssemblyCompany = "Alexey Zimarev";
        internal const System.String AssemblyCopyright = "Copyright © 2018 Alexey Zimarev";
        internal const System.String AssemblyVersion = "1.0.1.0";
        internal const System.String AssemblyFileVersion = "1.0.1.0";
        internal const System.String AssemblyInformationalVersion = "1.0.1+6.Branch.master.Sha.36961326774d41c78a6d083fb83fa8931507bb6e";
    }
}
